### ISSUE TITLE
I miss JQuery

### ISSUE THREAD

**Issue by ThomasCr** [forkingachild/helloworlds#2]
Would be nice if you add jquery

Example can found

https://mkyong.com/jquery/jquery-hello-world/

**Comment by 1nj3ct0rrr** [comment]
Your accuracy is admirable 👏
Here you are 👉 https://github.com/1nj3ct0rrr/HelloWorlds/blob/main/Languages/JQuery.html

Thanks for your help 🤩

**Comment by forkingachild** [comment]
> Would be nice if you add jquery
> 
> Example can found
> 
> https://mkyong.com/jquery/jquery-hello-world/

Your accuracy is admirable clap
Here you are point_right https://github.com/1nj3ct0rrr/HelloWorlds/blob/main/Languages/JQuery.html

Thanks for your help star_struck
